id: I5846C5C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:12:31+00:00'
last_modified: '2022-06-08T06:34:23.019148+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3703
  title: རྒྱུད་བླ་མའི་མཆན་འགྲེལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0B98:
      image_group_id: I1KG3738
      title: ''
      total_pages: 156
      order: 1
      base_file: 0B98.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
